//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeCritic.Client.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CosmeCriticDBEntities : DbContext
    {
        public CosmeCriticDBEntities()
            : base("name=CosmeCriticDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AltKategoriler> AltKategoriler { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Markalar> Markalar { get; set; }
        public virtual DbSet<OzellikDetay> OzellikDetay { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunPuan> UrunPuan { get; set; }
        public virtual DbSet<UrunYorum> UrunYorum { get; set; }
        public virtual DbSet<UyeFavoriListe> UyeFavoriListe { get; set; }
        public virtual DbSet<Uyeler> Uyeler { get; set; }
    }
}
