//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeCritic.Client.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunPuan
    {
        public int PuanID { get; set; }
        public int UyeId { get; set; }
        public int UrunId { get; set; }
        public int PuanDegeri { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
